### ISSUE TITLE
Revolution PI Connect recognized as PI Compact

### ISSUE THREAD

**Issue by LuanVorle** [RevolutionPi/piControl#104]
I'm using a custom image and compiled piControl module from source.

When I test it with "piTest -d", it recognizes as "RevPi Compact V1.0".
I'm using RevolutionPi kernel an piControl in "revpi-5.10" branch.

What may be wrong?
Best regards,
Luan

**Comment by nbuchwitz** [comment]
How does the configuration file /etc/revpi/config.rsc look like? Which devicetree is loaded (dtoverlay in /boot/config.txt)?

**Comment by LuanVorle** [comment]
I don't have an /etc/revpi/config.rsc, since I'm not using Revolution PI structure.
I was with revpi-compact overlay. It was wrong.
But, I change it to "revpi-connect" and now I'm having the following error:
"problem at driver initialization"
"no piControl reset possible, a firmware update is running"

I'm using a Revolution Connect+, am I loading the correct overlay?

Best regards,
Luan

**Comment by iluminat23** [comment]
Hi Luan,

the `revpi-connect` overlay is correct for the RevPi Connect+, but the revpi-image does more then just adding the kernel and the piControl module. Depending on your use-case you need to make various modifications to your image. As this goes beyond the piControl kernel module, it would be great if you could move the questions to the Revolution Pi Forum (https://revolutionpi.com/forum/). There the Revolution Pi support team and other users can help you.
