### ISSUE TITLE
Make config.rsc friendlier to use for interfacing

### ISSUE THREAD

**Issue by lweberk** [RevolutionPi/piControl#3]
Hi,

I happen to have to parse the config.rsc for the groundwork to a bigger project with RevPi's I'm involved with, and could not help but notice some inconsistencies and potential compatibility risks along the way of figuring out what is what and how the whole fits together.

- Is there any reason to not directly reflect the structures in `piControl.h` in the serialized JSON? There are JSON fields that pack multiple struct fields, that then have to be "stringly interpreted".
- I notice some discrepancies between the types in the struct declarations and the JSON equivalent being used. Like the index of a particular `SEntryInfo` entry, inlined the declared structure as u16, yet outside as key in the JSON as string.
- Also no keys at all for SEntryInfo's at all. Would break at any position shifting change done to the structure.

Now all this might at first glance seem as nitpicking, but what I'm trying to say is that the format itself depends a lot on a custom tailored state machine to parse instead of encoding the information declaratively as probably intended. This makes it hard to see the JSON itself as a solid point of interfacing.
We use Rust, which essentially requires us in this case to basically imitate the `piConfig.c` state machine. If the structures where purely declarative (no additional intelligence in the FSM) we would get everything for free ^^.
Another way around might be providing an officially supported serialization/deserialization functionality of the `config.rsc` as a dynamic library for other programs to then wrap. Dynamic because it is critical for a wrapping program to break on breaking changes. Statically linking in the piConfig.c/h would mean potentially undefined behavior on upstream introducing breaking changes.

Any thoughts on this?

Best Regards,
~lwk

**Comment by mduckeck** [comment]
Hi Leonhard,

I was looking for a lightweight json parser that can be used in a kernel 
driver (plain C). piConfig.c is converting the output of the parser to 
data structures that are more easy to use later. I did not really care 
about the order of variables and so on.

We have some customers who parse the rsc-files, That's why we can't simply 
change the format any more.

What are you doing with the parsed values? Are you running the whole 
piControl with rust?

best regards,
Mathias



Leonhard Weber <notifications@github.com> schrieb am 15.12.2017 17:04:15:

> Von: Leonhard Weber <notifications@github.com>
> An: RevolutionPi/piControl <piControl@noreply.github.com>, 
> Kopie: Subscribed <subscribed@noreply.github.com>
> Datum: 15.12.2017 17:04
> Betreff: [RevolutionPi/piControl] Make config.rsc friendlier to use for 
interfacing (#3)
> 
> Hi,
> I happen to have to parse the config.rsc for the groundwork to a bigger 
> project with RevPi's I'm involved with, and could not help but notice 
some 
> inconsistencies and potential compatibility risks along the way of 
figuring 
> out what is what and how the whole fits together.
> Is there any reason to not directly reflect the structures in 
piControl.h in 
> the serialized JSON? There are JSON fields that pack multiple struct 
fields, 
> that then have to be "stringly interpreted".
> I notice some discrepancies between the types in the struct declarations 
and 
> the JSON equivalent being used. Like the index of a particular 
SEntryInfo 
> entry, inlined the declared structure as u16, yet outside as key in the 
JSON as string.
> Also no keys at all for SEntryInfo's at all. Would break at any position 

> shifting change done to the structure.
> Now all this might at first glance seem as nitpicking, but what I'm 
trying to 
> say is that the format itself depends a lot on a custom tailored state 
machine
> to parse instead of encoding the information declaratively as probably 
> intended. This makes it hard to see the JSON itself as a solid point of 
interfacing.
> We use Rust, which essentially requires us in this case to basically 
imitate the 
> piConfig.c state machine. If the structures where purely declarative (no 

> additional intelligence in the FSM) we would get everything for free ^^.
> Another way around might be providing an officially supported 
serialization/
> deserialization functionality of the config.rsc as a dynamic library for 
other
> programs to then wrap. Dynamic because it is critical for a wrapping 
program 
> to break on breaking changes. Statically linking in the piConfig.c/h 
would 
> mean potentially undefined behavior on upstream introducing breaking 
changes.
> Any thoughts on this?
> Best Regards,
> ~lwk
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the 
thread.[Bild entfernt]

**Comment by lweberk** [comment]
Hello Mathias,

tough thing to incorporate –with all its tradeoffs– in a kernel module to begin with, even with its fairly straight forward notation. I can sympathize with your motivations. 

If you say the RSC schema is to be considered "frozen", then its currently good enough for me. The most important thing for us is the guarantee that it will not change. Then comes change being explicitly reflected.

We need the values to mesh multiple RevPi's together at a higher level of abstraction. It should also allow for virtual IO's across the network and fully virtualized devices for simulation/testing/faultinjection purposes. That includes a IO name resolution/aliasing layer on top of what the RSC file exposes.
Nope, we do not touch piControl from Rust. Maybe down the road, but then probably only in ways pictory is already doing.

I consider this issue as closed. My resolution so far is to narrow the view on the RSC file to read-only (because of type and structural mismatches) and frozen in its current form (due to dependents on current form). No explicit schema versioning and enforcement possible at this time (missing version tag in JSON). Will revisit once an imminent need to push any of the aforementioned limitations arises.

Best Regards,
~lwk
