### ISSUE TITLE
Any plans on supporting linux-5.4.y (or later)?

### ISSUE THREAD

**Issue by jaapcrezee** [RevolutionPi/piControl#33]
See title ;).

I am trying to get this module compiled for a linux-5.4.y kernel (or newer, 5.10.y is now the default RPI tree).
Or even better, can I use external modules (like the DIO) without having a kernel driver? I am not interested in RT, I just want it to work with a vanilla kernel preferably from userspace only.

**Comment by nbuchwitz** [comment]
Hi Jaap, better late than never :-) Our current development regarding the 5.10 support can be found here https://github.com/RevolutionPi/piControl/tree/devel/revpi-5.10
