### ISSUE TITLE
ksz8851ProcessInterrupt: serious error

### ISSUE THREAD

**Issue by ulrich06** [RevolutionPi/piControl#4]
Hello,

We are facing a _ksz8851ProcessInterrupt: serious error_ using KUNBUS DeviceNet Gateway. 
In /var/log/kern.log, we have the following entries (and both Power and MS LEDs turn flashing red) :
```
Dec  4 00:12:27 RevPi100257 kernel: [36405.378660] piControl: Module L: Link check   Module R: run no data
Dec  4 00:12:27 RevPi100257 kernel: [36405.383607] piControl: Module L: Link check   Module R: run
Dec  4 00:14:27 RevPi100257 kernel: [36525.487958] piControl: 0: ksz8851ProcessInterrupt: serious error 0xffff
Dec  4 00:14:27 RevPi100257 kernel: [36525.488379] piControl: ksz8851PacketRead(0) wrong chip id 33224 != 34930
Dec  4 00:14:27 RevPi100257 kernel: [36525.492918] piControl: Module L: Link check   Module R: Link check
Dec  4 00:14:27 RevPi100257 kernel: [36525.742946] piControl: 0: ksz8851ProcessInterrupt: serious error 0x226
Dec  4 00:14:27 RevPi100257 kernel: [36525.742956] piControl: ksz8851ReInit(0)
Dec  4 00:14:29 RevPi100257 kernel: [36527.327958] piControl: ksz8851ReInit(0)
Dec  4 00:14:31 RevPi100257 kernel: [36529.417966] piControl: ksz8851ReInit(0)
Dec  4 00:14:33 RevPi100257 kernel: [36531.507967] piControl: ksz8851ReInit(0)
Dec  4 00:14:35 RevPi100257 kernel: [36533.597978] piControl: ksz8851ReInit(0)
```

We use a RevPi Core 3 upgraded with Linux Stretch (https://revolution.kunbus.de/shop/de/stretch).

Best,

**Comment by l1k** [comment]
We've reimplemented the gateway communication from scratch and plan to release a new kernel package (and an image with that kernel package) early next year. However we're still ironing out stability issues that might occur under high load. The log you've posted above is from the old code and trying to fix that doesn't make much sense. The new code is on the <a href="https://github.com/RevolutionPi/piControl/commits/skb">skb</a> branch, it must be compiled against the <a href="https://github.com/revolutionpi/linux/commits/revpi-4.9-skb">revpi-4.9-skb</a> kernel branch using <a href="https://github.com/revolutionpi/kernelbakery">kernelbakery</a>. Are you able to compile a kernel package yourself using those branches? If not I guess we may be able to furnish you with a ready-to-install package if you're willing to serve as a beta tester or something like that.

**Comment by l1k** [comment]
FWIW, I've pushed out new versions of the three above-linked branches today which fix all known gateway-related issues.

There is one non-gateway issue remaining wherein piControl will fail to load if listed in `/etc/modules`. It needs to be loaded manually after the system has booted (or from `/etc/rc.local` with a delay). This is caused by an incorrect ordering with respect to the `spi-bcm2835` module which I'll look into in early January.

**Comment by ulrich06** [comment]
Thank you for that detailed answer!
I was able to compile the kernel but I will have to wait until early January to deploy it at our customer's site. I will keep you informed of the results.

**Comment by ulrich06** [comment]
Ok, I've deployed the new kernel with its updated piControl on a testbed (unfortunately, without any fieldbus connected to it... we have to wait for january).
```
Dec 21 13:57:25 RevPi100257 kernel: [   70.388138] piControl: loading out-of-tree module taints kernel.
Dec 21 13:57:25 RevPi100257 kernel: [   70.391575] piControl: built: Fri Dec 21 11:12:55 CET 2018
Dec 21 13:57:25 RevPi100257 kernel: [   70.391594] piControl: RevPi Core
Dec 21 13:57:25 RevPi100257 kernel: [   70.391602] piControl: MAJOR-No.  : 242
Dec 21 13:57:25 RevPi100257 kernel: [   70.391926] piControl: MAJOR-No.  : 242  MINOR-No.  : 0
Dec 21 13:57:25 RevPi100257 kernel: [   70.394174] piControl: line 1, col 3800: [code=8] unexpected char
Dec 21 13:57:25 RevPi100257 kernel: [   70.394849] uart-pl011 3f201000.serial: no DMA platform data
Dec 21 13:57:25 RevPi100257 kernel: [   70.394903] piControl: filp_open -1213402112
Dec 21 13:57:25 RevPi100257 kernel: [   70.394975] piControl: set priority of spi0 to 54
Dec 21 13:57:25 RevPi100257 kernel: [   70.395082] piControl: piIO thread started
Dec 21 13:57:25 RevPi100257 kernel: [   70.395089] piControl: RevPiDevice_init()
Dec 21 13:57:25 RevPi100257 kernel: [   70.395095] piControl: Enter Init State
Dec 21 13:57:25 RevPi100257 kernel: [   70.395099] piControl: PADS 0 = 0x1b   slew=1  hyst=1  drive=3
Dec 21 13:57:25 RevPi100257 kernel: [   70.395105] piControl: PADS 1 = 0x1b   slew=1  hyst=1  drive=3
Dec 21 13:57:25 RevPi100257 kernel: [   70.395109] piControl: PADS 2 = 0x1b   slew=1  hyst=1  drive=3
Dec 21 13:57:25 RevPi100257 kernel: [   70.395123] piControl: piControlInit done
Dec 21 13:57:25 RevPi100257 kernel: [   70.395804] piControl: Enter PresentSignalling1 State
Dec 21 13:57:25 RevPi100257 kernel: [   70.434951] piControl: Enter InitialSlaveDetectionRight State
Dec 21 13:57:25 RevPi100257 kernel: [   70.435516] piControl: Enter InitialSlaveDetectionLeft State
Dec 21 13:57:25 RevPi100257 kernel: [   70.436235] piControl: Enter ConfigLeftStart State
Dec 21 13:57:25 RevPi100257 kernel: [   70.447028] piControl: Enter ConfigDialogueLeft State
Dec 21 13:57:25 RevPi100257 kernel: [   70.491106] piControl: piIoComm_sendRS485Tel(GetDeviceInfo) failed 2
Dec 21 13:57:25 RevPi100257 kernel: [   70.551051] piControl: piIoComm_sendRS485Tel(GetDeviceInfo) failed 2
Dec 21 13:57:25 RevPi100257 kernel: [   70.601035] piControl: piIoComm_sendRS485Tel(GetDeviceInfo) failed 2
Dec 21 13:57:25 RevPi100257 kernel: [   70.651037] piControl: piIoComm_sendRS485Tel(GetDeviceInfo) failed 2
Dec 21 13:57:25 RevPi100257 kernel: [   70.651565] piControl: Enter EndOfConfig State
Dec 21 13:57:25 RevPi100257 kernel: [   70.651565] 
Dec 21 13:57:25 RevPi100257 kernel: [   70.651573] piControl: Device  0: Addr  0 Type  95  Act 1  In   6 Out   5
Dec 21 13:57:25 RevPi100257 kernel: [   70.651578] piControl:            input offset      0  len   6
Dec 21 13:57:25 RevPi100257 kernel: [   70.651581] piControl:            output offset     6  len   5
Dec 21 13:57:25 RevPi100257 kernel: [   70.651585] piControl:            serial number 1  version 1.2
Dec 21 13:57:25 RevPi100257 kernel: [   70.651588] piControl: 
Dec 21 13:57:25 RevPi100257 kernel: [   70.651597] piControl: After Adjustment
Dec 21 13:57:25 RevPi100257 kernel: [   70.651602] piControl: Device  0: Addr  0 Type  95  Act 1  In   6 Out   5
Dec 21 13:57:25 RevPi100257 kernel: [   70.651605] piControl:            input offset      0  len   6
Dec 21 13:57:25 RevPi100257 kernel: [   70.651608] piControl:            output offset     6  len   5
Dec 21 13:57:25 RevPi100257 kernel: [   70.651611] piControl: 
Dec 21 13:57:25 RevPi100257 kernel: [   70.771047] piControl: start data exchange
Dec 21 13:57:25 RevPi100257 kernel: [   71.011065] piControl: set BridgeState to running
```
I can write values in variable using their offset address, e.g.:
```
piTest -w 6,4,5
Write value 5 hex (=5 dez) to offset 6.
```
but I cannot use their exported name from PiCtory :/ any hint? 
```
piTest -w RevPiLED,5
Cannot find variable 'RevPiLED'
```

**Comment by l1k** [comment]
Hm, I'm not aware of a regression in that area. But I'll definitely test this when I return to the office in 2 weeks. Thanks a lot for giving the current branches a spin!

**Comment by l1k** [comment]
I've pushed an updated version of the <a href="https://github.com/RevolutionPi/piControl/commits/skb">skb branch</a> which contains commit e53803482b0a to address the boot ordering issue with the spi driver.

I was able to reproduce the variable issue you've reported above, it was caused by a mistake I made in commit 23d281567e24. I've rebased the branch and fixed it in commit b8656190ef31. Thanks a lot for spotting this, much appreciated!

There's two or three more esoteric bugs that I still need to chase down but the gateway communication should be stable with the current version of the skb branch.

**Comment by l1k** [comment]
FWIW we've released a new image last Friday which should cure gateway-related issues. Existing systems can be updated with "sudo apt-get update && sudo apt-get upgrade". If you're only interested in fixing the gateway communication then it's sufficient to update the "raspberrypi-kernel" and "revpi-tools" packages. Could you test whether this new release works for you?

**Comment by iluminat23** [comment]
If this issue is not resolved to your satisfaction, you may reopen it.
