### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by thalesmaoa** [RevolutionPi/piControl#63]
I got to know Revolution Pi last week. I'm committed to replace my Siemens PLC. However, I can't find where can I get support. There is no eMail, phone number or even a chat channel. Forum didn't allow my registration. Is this project ongoing?

**Comment by manuelfgm** [comment]
Same issue here. I tried to sign up into the forum and never get activation link. No email, no chat. Nothin.

**Comment by iluminat23** [comment]
@thalesmaoa @manuelfgm This project is alive. Sorry we missed your issues here. We get most of our feedback from the Forum so we lost the github issues out of sight.
I forwarded your issue with the forum registration to our support team.
