### ISSUE TITLE
Minimum safe value for INTERVAL_IO_COMM

### ISSUE THREAD

**Issue by KaSroka** [RevolutionPi/piControl#7]
What's the minimum safe value for `INTERVAL_IO_COMM`?

I want to achieve ~1ms delay between python code writing to `/dev/piControl0` to pin reaction (or the other way around). Also, it would be really nice to have timings configurable at runtime.

**Comment by KaSroka** [comment]
I've noticed that this doesn't change the IO latency, is there any other limitation?

**Comment by iluminat23** [comment]
Hi Kamil,

sorry for the long delay. If this is still an issue for you, please use our support forum: https://revolution.kunbus.de/forum/

Best regards,
Philipp
